//
// LocationDetailResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class LocationDetailResponse: JSONEncodable {

    public var location: Location?
    public var comment: [LocationDetailResponseComment]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["location"] = self.location?.encodeToJSON()
        nillableDictionary["comment"] = self.comment?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
