//
// LocationsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class LocationsAPI: APIBase {
    /**

     - parameter locationId: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func requestLocationDetail(locationId: Int32, completion: @escaping ((_ data: LocationDetailResponse?,_ error: Error?) -> Void)) {
        requestLocationDetailWithRequestBuilder(locationId: locationId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /locations/{locationId}
     - examples: [{contentType=application/json, example={
  "location" : {
    "subtitle" : "aeiou",
    "id" : 0,
    "title" : "aeiou",
    "lat" : 6.0274563,
    "long" : 1.4658129
  },
  "comment" : [ {
    "imageUrl" : "aeiou",
    "name" : "aeiou",
    "content" : "aeiou"
  } ]
}}]
     
     - parameter locationId: (path)  

     - returns: RequestBuilder<LocationDetailResponse> 
     */
    open class func requestLocationDetailWithRequestBuilder(locationId: Int32) -> RequestBuilder<LocationDetailResponse> {
        var path = "/locations/{locationId}"
        path = path.replacingOccurrences(of: "{locationId}", with: "\(locationId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<LocationDetailResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func requestLocations(completion: @escaping ((_ data: LocationsResponse?,_ error: Error?) -> Void)) {
        requestLocationsWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /locations
     - examples: [{contentType=application/json, example={
  "locations" : [ {
    "subtitle" : "aeiou",
    "id" : 0,
    "title" : "aeiou",
    "lat" : 6.0274563,
    "long" : 1.4658129
  } ]
}}]

     - returns: RequestBuilder<LocationsResponse> 
     */
    open class func requestLocationsWithRequestBuilder() -> RequestBuilder<LocationsResponse> {
        let path = "/locations"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<LocationsResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
